universe        = vanilla
environment = "LD_LIBRARY_PATH=/afs/cern.ch/user/h/huangxi/Tools/pythia8310/lib:$LD_LIBRARY_PATH"
executable      = NSC3.sh
arguments       = $(Process)
output          = logs/out_$(Process).log
error           = logs/err_$(Process).log
log             = logs/condor.log
# should_transfer_files = YES
# transfer_input_files = event0
# transfer_output_files = Playground
+MaxRuntime =200000
queue 35
